# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
- task: BatchScript@1
  displayName: 'Tosca-CI'
  inputs:
    filename: '"C:\Program Files (x86)\TRICENTIS\Tosca Testsuite\ToscaCommander\ToscaCI\Client\ToscaCIClient.exe"'
    arguments: '-m distributed -t junit -r "C:\Users\SEENA\Downloads\Results.xml" '

