# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  #vmImage: ubuntu-latest
   vmImage: Tosca Agent
   
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: BatchScript@1
  inputs:
    filename: '"C:\Program Files (x86)\TRICENTIS\Tosca Testsuite\ToscaCommander\ToscaCI\Client\ToscaCIClient.exe"'
    arguments: '-m distributed -t junit -r "C:\Users\SEENA\Downloads\Results.xml"'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
